AWSTemplateFormatVersion: 2010-09-09
Description: This contains the DNS setup for lancerin.com

Resources:
  LancerinComHz:
    Type: AWS::Route53::HostedZone
    Properties:
      Name: lancerin.com
      HostedZoneConfig:
        Comment: Hosted zone for lancerin.com
      HostedZoneTags:
        - Key: "cost-center"
          Value: "lancerin.com"

  LancerinComRsGroup:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      Comment: All records necessary to verify the lancerin.com R53 setup with SES.
      HostedZoneId: !Ref LancerinComHz
      RecordSets:
      - Name: _amazonses.lancerin.com
        Type: TXT
        TTL: '60'
        ResourceRecords:
          - "\"oirEBLXuWgPN/VV+BI1862RcwGi4UJuzxbZmcmMLu4E=\""
      - Name: 3q2sfelukswmg42pzbxixzdplxgmyyng._domainkey.lancerin.com
        Type: CNAME
        TTL: '60'
        ResourceRecords:
          - 3q2sfelukswmg42pzbxixzdplxgmyyng.dkim.amazonses.com
      - Name: knysavpc2hfoafhycareasfny3nr7exl._domainkey.lancerin.com
        Type: CNAME
        TTL: '60'
        ResourceRecords:
          - knysavpc2hfoafhycareasfny3nr7exl.dkim.amazonses.com
      - Name: bejhqygjzkhtu3qmc75nnqocvkykhetz._domainkey.lancerin.com
        Type: CNAME
        TTL: '60'
        ResourceRecords:
          - bejhqygjzkhtu3qmc75nnqocvkykhetz.dkim.amazonses.com
      - Name: lancerin.com
        Type: MX
        TTL: '60'
        ResourceRecords:
          - 10 inbound-smtp.eu-west-1.amazonaws.com
      - Name: lancerin.com
        Type: TXT
        TTL: '3600'
        ResourceRecords:
          - "\"v=spf1 include:amazonses.com ~all\""


Outputs:
  LancerinComHzId:
    Description: Hosted Zone Id for lancerin.com
    Value: !Ref LancerinComHz
    Export: 
      Name: !Sub '${AWS::StackName}-LancerinComHzId'

  LancerinComHzName:
    Description: Hosted Zone Name for lancerin.com
    Value: lancerin.com
    Export: 
      Name: !Sub '${AWS::StackName}-LancerinComHzName'