AWSTemplateFormatVersion: 2010-09-09
Description: This contains the shared setup for SES to receive and send emails for lancerin.com .

Resources: 
  LancerinComMailBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties: 
      AccessControl: Private
      BucketName: lancerin-com-mail-eu-west-1
      LifecycleConfiguration:
        Rules:
          - Id: Remove mail older than 30 days
            ExpirationInDays: 30
            Prefix: inbox
            Status: Enabled
      # NotificationConfiguration can only be added when lambda ia already created (duh!)
      NotificationConfiguration:
        LambdaConfigurations:
          - Event: s3:ObjectCreated:Put
            Filter:
              S3Key:
                Rules:
                  # Special characters like @ need percent-encoding
                  - Name: prefix
                    Value: inbox/federico%40lancerin.com/
            Function: !ImportValue lambda-mail-forwarder-MailForwarderArn
      Tags:
        - Key: cost-center
          Value: mail-lancerin-com

  LancerinComMailBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref LancerinComMailBucket
      PolicyDocument:
        Statement:
          - Sid: AllowSESPuts
            Effect: Allow
            Action: s3:PutObject
            Principal:
              Service: ses.amazonaws.com
            Resource: !Sub '${LancerinComMailBucket.Arn}/*'
            Condition:
              StringEquals:
                aws:Referer: "271223117946"

  LancerinComRecRuleSet:
    Type: AWS::SES::ReceiptRuleSet
    Properties: 
      RuleSetName: receipt-rule-lancerin-com

  LancerinComNotificationTopic:
    Type: AWS::SNS::Topic
    Properties: 
      DisplayName: lancerin-com-notification-topic
      Subscription: 
        - Endpoint: federico.lancerin@gmail.com
          Protocol: email
      TopicName: lancerin-com-notification-topic

Outputs:
  LancerinComMailBucket:
    Description: Bucket name for lancerin.com email
    Value: !Ref LancerinComMailBucket
    Export: 
      Name: !Sub '${AWS::StackName}-LancerinComMailBucket'

  LancerinComMailBucketArn:
    Description: Bucket name for lancerin.com email
    Value: !GetAtt LancerinComMailBucket.Arn
    Export: 
      Name: !Sub '${AWS::StackName}-LancerinComMailBucketArn'

  LancerinComRecRuleSet:
    Description: Bucket name for lancerin.com email
    Value: !Ref LancerinComRecRuleSet
    Export: 
      Name: !Sub '${AWS::StackName}-LancerinComRecRuleSet'
